# Dockerfile.step2
FROM rust:1.94-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml ./
COPY Cargo.lock* ./
COPY src ./src

RUN cargo build --release

EXPOSE 8080
CMD ["./target/release/note-api"]
