# Dockerfile.step2
FROM golang:1.24-alpine

WORKDIR /app

# Git 설치 (go mod download에 필요할 수 있음)
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o main .

EXPOSE 8080
CMD ["./main"]
